### ISSUE TITLE
Remove orphaned environments after 30 days

### ISSUE THREAD

**Issue by Richard87** [equinor/radix-operator#1097]
We should cleanup old orphaned namespaces that have been deleted after 7 days

Atleast this:
- Restore soft-deleted RadixEnvironments in velero
- Warn in web-console that removed environments will be deleted after 30 days
- Delete RE/namespaces etc after 30 days (maybe use finalizers?)

Add a new re-sync every 24 hrs, delete if older than 30 days and marked orphaned

DoD
No environment will be marked orphaned more than 30 days

**Comment by nilsgstrabo** [comment]
implemented
