### ISSUE TITLE
Refine scheduled job batch statuses

### ISSUE THREAD

**Issue by satr** [equinor/radix-operator#1101]
Feedback from users shows inconsistent status of batches with completed and/or failed jobs. It need to be refined.
_Typical statuses_:
- Batch created, no jobs created yet
- Batch exists, jobs created, no jobs started
- Some jobs started, other is waiting (not started, some of them can stay in this state forever, due to f.ex. too large resources requested)
- Some jobs failed, some of them restarted after fail (when [backuffLimit](https://www.radix.equinor.com/radix-config#backofflimit) > 0)
- Some jobs succeeded , some failed, some is not started
- All jobs completed:
  - all succeeded
  - all failed
  - some succeeded, some failed

An example for the batch state (just for a duscussion):
- Created(batch created, maybe jobs run, some completed of failed)
- Completed(all jobs completed)
- Failed (all jobs failed) 

Suggestions from the discussion in slack:
- Maybe add a status Successful (all jobs succeeded)?and possibly Terminated.
- We use batch for one of our applications. Each job make a callback to the completed endpoint (I guess our code is like this because it was implemented before the hook functionality was introduced). Here we check for all jobs in batch and check that all are completed: Support we get a successful batch when all jobs are successful
- +1 on the Successful (all jobs succeeded). Terminated or Stopped if the batch was stopped before all jobs completed would also be nice.
- If one or few (not all) jobs where stopped? I would expect POST /api/v1/batches/{batchName}/stop to result in batch status Stopped
 Stopping one or few jobs of a batch, I guess with POST /api/v1/batches/{batchName}/jobs/{jobName}/stop (?), isn't something we usually do. I guess the batch itself hasn't been stopped so the maybe the stopped jobs just don't "count" towards the batch status? 
CC: @equinor-ruaj, @ingeknudsen, @rwiker

**Comment by emirgens** [comment]
Come up with two well described alternatives.
Will ask for voting from the community.
Implement the most voted option

**Comment by emirgens** [comment]
Result from feedback from our users: 
Which Batch Job Status alternative? 
Results (10 voters):
███████ (7) :b:
[Described](https://github.com/equinor/radix-private/blob/master/community/outreach/feedback-batch-status.md) in radix-private repo
