### ISSUE TITLE
Current client generator is end of life

### ISSUE THREAD

**Issue by Richard87** [equinor/radix-operator#1111]
Instead of using 
https://github.com/kubernetes/code-generator/blob/master/generate-groups.sh

we should use
https://github.com/kubernetes/code-generator/blob/master/kube_codegen.sh

Example repo - usage here:
https://github.com/kubernetes/sample-controller/blob/master/pkg/apis/samplecontroller/v1alpha1/types.go#L23
https://github.com/kubernetes/sample-controller/blob/master/hack/update-codegen.sh

But is should be tweaked a bit to look in GOPATH, not in local vendor folder (that usually doesnt exist)

**Comment by nilsgstrabo** [comment]
https://github.com/equinor/radix-operator/pull/1118
