### ISSUE TITLE
Build using buildkit and cache does not work

### ISSUE THREAD

**Issue by emirgens** [equinor/radix-operator#1113]
Using Buildah (buildkit) and mounting cache does not work.

**Sample error:**

> time="2024-05-08T11:35:44Z" level=error msg="Failed to create temp directory for user: mkdir /var/tmp/containers-user-0: no such file or directory"
> Error: unable to make rootless runtime: mkdir /root/rundir: read-only file system
![image](https://github.com/equinor/radix-operator/assets/5749715/3c23c4fe-6833-40e2-af55-6d0e5c3c1168)

DoD
Users can use cache mount types in Dockerfile with the Buildah pipeline.

**Comment by satr** [comment]
Folders `/tmp` and `/var` are writable now for both `ACR` build and `buildah`, they can be used for cashing like this
```
RUN --mount=type=cache,target=/var/your-folder/ \
    apk add --update-cache \
        curl
```
