### ISSUE TITLE
define rule(s) for max value of "resources.limits.memory" in radixconfig

### ISSUE THREAD

**Issue by nilsgstrabo** [equinor/radix-operator#952]
We need to come up with some kind of rule/limitation for what users can set for `resources.limits.memory` in radixconfig.

The issue we had in C2 was most likely caused by a misconfiguration where this field was set to 512Gi. This caused critical system processes on nodes where these pods were running, to be OOMKilled, which ultimately lead to unresponsive applications.

Perhaps disallow `limits.memory` to be more than 1Gi than `requests.memory`? Let's discuss

DoD
Only 1-one Memory specification in radixconfig.yaml, only "requested memory"
CPU no changes

**Comment by emirgens** [comment]
First - list of all components with these config specified

**Comment by satr** [comment]
Implemented.
`limits.memory` is automatically set to value `requests.memory` for `RadixApplication` and in LimitRange-es
