### ISSUE TITLE
Apply radixconfig to a Radix application

### ISSUE THREAD

**Issue by satr** [equinor/radix-operator#973]
`radixconfig` has options, which do not require re-deployment, e.g. aliases, changes in app environment.
It can be valuable to have an option to apply changes in radxiconfig to the Radix application, for ex. running a new type of pipeline job. Button on Radix console and a command in Radix CLI

**Comment by emirgens** [comment]
Refinement:
Agree on where to add the button/choice to start a "apply config pipeline job"
